name: Update Commit Counters

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day 00:00
  workflow_dispatch:

jobs:
  update_commit_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Total Commit Days (Excluding github-actions)
        id: total_commit_days
        run: |
          total_days=$(git log --format="%ad %an" --date=short | grep -v "github-actions" | cut -d ' ' -f1 | uniq | wc -l)
          echo "Total commit days: $total_days"
          echo "{total_days}={$total_days}" >> $GITHUB_STATE

      - name: Get Weekly Commit Days (Excluding github-actions)
        id: weekly_commit_days
        run: |
          # Get the start of the week (Sunday)
          sunday=$(date -d "last sunday" +"%Y-%m-%d")
          weekly_days=$(git log --since="$sunday" --format="%ad %an" --date=short | grep -v "github-actions" | cut -d ' ' -f1 | uniq | wc -l)
          echo "Weekly commit days: $weekly_days"
          echo "{weekly_days}={$weekly_days}" >> $GITHUB_STATE

      - name: Update README with Shields.io badges
        run: |
          total_days=${{ steps.total_commit_days.outputs.total_days }}
          weekly_days=${{ steps.weekly_commit_days.outputs.weekly_days }}

          # Construct the shields.io badge URLs
          total_commit_badge="![Total Commit Days](https://img.shields.io/badge/Total%20Commit%20Days-$total_days-brightgreen)"
          weekly_commit_badge="![Weekly Commit Days](https://img.shields.io/badge/Weekly%20Commit%20Days-$weekly_days-blue)"

          # Replace the existing badges in README.md
          sed -i 's|!\[Total Commit Days\](.*)|'"$total_commit_badge"'|g' README.md
          sed -i 's|!\[Weekly Commit Days\](.*)|'"$weekly_commit_badge"'|g' README.md

          # Push the changes back to the repository
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update commit days badges"
          git push